#!/usr/bin/env python3
"""Generate the destination project README from a modularization report."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def load_report(path: Path) -> dict[str, Any]:
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"Unable to read modularization report {path}: {exc}")

    required = (
        "project",
        "environment",
        "region",
        "account_id",
        "processed_categories",
        "skipped_categories",
        "source_resources",
        "source_imports",
        "destination_resources",
        "destination_imports",
        "modularized_resources",
        "preserved_native_resources",
        "categories",
        "skipped_category_details",
    )
    missing = [key for key in required if key not in report]
    if missing:
        fail(f"Report is missing required fields: {', '.join(missing)}")
    return report


def category_rows(report: dict[str, Any]) -> str:
    rows = []
    for item in report["categories"]:
        details = item["modularization"]
        rows.append(
            f"| `{item['category']}` | {item['status']} | "
            f"{details['source_resources']} | {details['destination_imports']} | "
            f"{len(details['modularized'])} | "
            f"{len(details['preserved_native'])} |"
        )
    return "\n".join(rows)


def skipped_section(report: dict[str, Any]) -> str:
    skipped = report["skipped_category_details"]
    if not skipped:
        return "No categories were skipped."
    return "\n".join(
        f"- `{item['category']}`: {item['reason']}" for item in skipped
    )


def render(report: dict[str, Any]) -> str:
    project = report["project"]
    environment = report["environment"]
    account_key = report.get("account_key", "")
    imports = report["destination_imports"]
    terraform_scope = (
        f"{account_key}/{environment}" if account_key else environment
    )
    report_scope = (
        f"{project}/{account_key}/{environment}"
        if account_key
        else f"{project}/{environment}"
    )

    return f"""# {project} Infrastructure as Code

This repository contains the Terraform configuration generated by
`tf-importer` for infrastructure that already exists in AWS. The generated
configuration was validated before publication and is intended to bring those
resources under Terraform management through import blocks.

## Generation summary

| Field | Value |
| --- | --- |
| Project | `{project}` |
| Environment | `{environment}` |
| AWS account | `{report['account_id']}` |
| AWS region | `{report['region']}` |
| Processed categories | {report['processed_categories']} |
| Skipped categories | {report['skipped_categories']} |
| Source resources | {report['source_resources']} |
| Source imports | {report['source_imports']} |
| Destination resources | {report['destination_resources']} |
| Destination imports | {imports} |
| Modularized resources | {report['modularized_resources']} |
| Native resources preserved | {report['preserved_native_resources']} |

## Imported resources by category

| Category | Status | Resources | Imports | Modularized | Native |
| --- | --- | ---: | ---: | ---: | ---: |
{category_rows(report)}

## Skipped categories

{skipped_section(report)}

## Validation guarantee

Every published category passed `terraform fmt`, `terraform validate`, and a
Terraform plan restricted to imports. The accepted sum of the category plans
is:

```text
Plan: {imports} to import, 0 to add, 0 to change, 0 to destroy.
```

If a future plan proposes add, change, or destroy actions, stop and investigate
the difference before continuing.

## Project structure

- `config/` contains the resource-to-module mapping.
- `modules/` contains reusable Terraform modules.
- `tag/` contains the shared tagging module.
- `terraform/{terraform_scope}/<category>/` contains one independently validated
  root configuration per resource category.

Each category has its own backend state and can be initialized, planned, and
operated independently.

## Safe usage

Authenticate to AWS account `{report['account_id']}` and select a category:

```bash
cd terraform/{terraform_scope}/<category>
terraform init
terraform validate
terraform plan
```

Review the plan and confirm that it contains imports only:
`N to import, 0 to add, 0 to change, 0 to destroy`.

`tf-importer` never runs `terraform apply`. Applying the generated configuration
is a separate, explicit operational decision.

## Git publication

Generated Terraform and inventory summaries can describe real AWS accounts and
may contain sensitive values. They are ignored by Git by default. Review and
sanitize the complete destination before explicitly selecting files for
publication. If publication is approved, the user may override the ignore rule
for an exact reviewed path with:

```bash
git add -f terraform/<reviewed-scope>
git add -f docs/inventory/<reviewed-scope>
```

`tf-importer` never stages, commits, pushes, or changes this decision.

## Inventory accountability

The sanitized cross-environment inventory summaries are available in
[`docs/inventory/`](docs/inventory/README.md). Detailed resource identities and
classification reasons remain only in the ignored `tf-importer` runtime
reports.

## Generation report

The detailed machine-readable report is produced by the source project at:

```text
reports/{report_scope}/modularization_pipeline.json
```

It records per-category resource addresses, modularized resources, preserved
native resources, missing imports, and orphan imports.
"""


def main() -> None:
    if len(sys.argv) != 3:
        fail(
            "Usage: generate_destination_readme.py "
            "<modularization-report.json> <destination-README.md>"
        )

    report_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    report = load_report(report_path)
    output_path.write_text(render(report), encoding="utf-8")


if __name__ == "__main__":
    main()
